[package]
name = "quix-cli"
version.workspace = true
edition = "2021"

[[bin]]
name = "quix"
path = "src/main.rs"

[dependencies]
proto = { path = "../proto" }
clap = { version = "4", features = ["derive"] }
serde_json.workspace = true
anyhow.workspace = true
tokio = { workspace = true, features = ["full"] }
interprocess = { version = "2.4.4", features = ["tokio"] }
sha2 = "0.11.0"
reqwest = { version = "0.13.5", default-features = false, features = ["rustls", "json", "http2", "charset"] }
