[package]
name = "quix-daemon"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "quixd"
path = "src/main.rs"

[dependencies]
proto = { path = "../proto" }
iroh.workspace = true
tokio.workspace = true
serde_json.workspace = true
anyhow.workspace = true
dirs = "7.0.0"
tun-rs = { version = "2.8.9", features = ["async_tokio"] }
sha2 = "0.11.0"
interprocess = { version = "2.4.4", features = ["tokio"] }
hex = "0.4.3"
serde = { workspace = true, features = ["derive"] }
getrandom = "0.4.3"
